spring.application.name=API-GATEWAY

server.port=8088
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

#for rate limiter
spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.cloud.gateway.server.webflux.routes[0].id=productServiceMapping
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/products/**
spring.cloud.gateway.server.webflux.routes[0].uri=lb://PRODUCT-SERVICE

spring.cloud.gateway.server.webflux.routes[1].id=paymentServiceMapping
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/payments/**
spring.cloud.gateway.server.webflux.routes[1].uri=lb://PAYMENT-SERVICE

spring.cloud.gateway.server.webflux.routes[2].id=authtServerMapping
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/auth/**
spring.cloud.gateway.server.webflux.routes[2].uri=lb://AUTH-SERVER

spring.cloud.gateway.server.webflux.routes[0].filters[0].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.redis-rate-limiter.replenishRate=10
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.redis-rate-limiter.burstCapacity=10
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.key-resolver=#{@ipKeyResolver}